# Black formatting
[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    .venv
    | migrations
    | static
    | templates
    | tools
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
virtual_env = ".venv"
skip_glob = ["**/migrations/*.py"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "alexandru_optica_app.settings.testing"