# Black formatting
[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    .venv
    | migrations
    | static
    | templates
    | tools
)/
'''

[tool.flake8]
max-line-length = 88
exclude = ".venv,migrations,static,templates,tools"

[tool.isort]
profile = "black"
line_length = 88
virtual_env = ".venv"
