# Generated by Django 4.2.7 on 2023-11-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("optica_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.TextField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("IGC", "ItsGetComplicated"),
                        ],
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        related_name="vouchers", to="optica_app.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                (
                    "payment_ref",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="optica_app.voucher",
                    ),
                ),
            ],
        ),
    ]
