# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com>
# project: AlexandruGlassApp
# github: https://github.com/boot-sandre/alexandru-glass-app/
# Generated by Django 4.2.7 on 2023-11-07 19:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_od_spheric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fare_od_cylindric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fare_od_axis', models.IntegerField(blank=True, null=True)),
                ('fare_os_spheric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fare_os_cylindric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fare_os_axis', models.IntegerField(blank=True, null=True)),
                ('fare_pupillary_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('aproape_od_spheric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aproape_od_cylindric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aproape_od_axis', models.IntegerField(blank=True, null=True)),
                ('aproape_os_spheric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aproape_os_cylindric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aproape_os_axis', models.IntegerField(blank=True, null=True)),
                ('aproape_pupillary_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('intermediar_od_spheric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intermediar_od_cylindric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intermediar_od_axis', models.IntegerField(blank=True, null=True)),
                ('intermediar_os_spheric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intermediar_os_cylindric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intermediar_os_axis', models.IntegerField(blank=True, null=True)),
                ('intermediar_pupillary_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='GlassApp.order')),
            ],
            options={
                'verbose_name': 'Prescription Detail',
                'verbose_name_plural': 'Prescription Details',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='GlassApp.order')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='GlassApp.order')),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='GlassApp.order')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
