# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com>
# project: AlexandruGlassApp
# github: https://github.com/boot-sandre/alexandru-glass-app/
# Generated by Django 4.2.7 on 2023-11-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlassApp', '0002_order_created_order_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
