# Generated by Django 4.2.7 on 2023-11-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlassApp', '0002_order_created_order_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
