# Generated by Django 4.2.7 on 2023-11-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlassApp', '0003_rename_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='GlassApp.order'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='GlassApp.order'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='GlassApp.order'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='GlassApp.order'),
        ),
    ]
